### ISSUE TITLE
The ER diagram is missing attributes (M)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#156]
The `User` entity in the ERD is missing the attribute `LastDDLOperation`.

Note: PNG versions need to be generated in 100% and 80% sizes for the updated ERD. See comments in PR #153 for additional information.

**Comment by KevinKelly25** [comment]
Added PR #157 to address this issue in docs. However, I still need to modify the M2 design document in the wiki to reflect this missing attribute.

**Comment by KevinKelly25** [comment]
Updated [M2 Design Outline](https://github.com/DASSL/ClassDB/wiki/User-and-Team-Management-(M2))

**Comment by smurthys** [comment]
@KevinKelly25 I see the original error is in the design outline. Thanks for spotting and fixing that.

**Comment by KevinKelly25** [comment]
Fixed by PR #157
