### ISSUE TITLE
ClassDB.PostgresLog is not temporary (W)

### ISSUE THREAD

**Issue by srrollo** [DASSL/ClassDB#162]
`ClassDB.PostgresLog` is not created as a temporary table, however its use is strictly temporary - it is filled and then truncated withing `importConnectionLog()` only. It should be created as a temporary table within `importConnectionLog()`.

**Comment by smurthys** [comment]
It seems this is a duplicate of #204 (my fault creating 204).

I am closing this issue because #204 already has some metadata associated.
