### ISSUE TITLE
Connection activity logging only records the connection timestamp (E)

### ISSUE THREAD

**Issue by srrollo** [DASSL/ClassDB#163]
The Postgres connection logs record additional information ClassDB does not user, namely `connection_from` and `application_name`. It would be useful to record these attributes in the connection activity log.

**Comment by smurthys** [comment]
Adding this comment to make it visible. I recommend using this issue to capture the need to add host, application, and other information discussed in this morning's meeting.

I am adding this to the M3 list so it gets attention. We can remove it from the M3 pipeline if a discussion recommends so.

**Comment by srrollo** [comment]
Adding a few comments based on yesterday's discussion:
- Setting `log_destination` to `csvlog` standardizes the log line format to match the format described in [section 19.8.4](https://www.postgresql.org/docs/9.6/static/runtime-config-logging.html), regardless of other settings like `log_line_prefix`. Other settings can effect when new lines are written, but not their structure.
- `application_name` is not actually a server parameter, rather, it is a environment variable set by the client. Confusingly, despite its inclusion in the logging docs, there is no server parameter to enable or disable logging `application_name`.
- According to the linked docs, `application_name` is recorded using `csvlog`, however an initial test on my system shows only a blank string logged as application name (despite `SHOW application_name` returning `psql`). However, manually setting `application_name` does cause the new value to be logged for the duration of the session. This will require further testing.

**Comment by smurthys** [comment]
Both the `-d` command-line option to `psql` and the `\c` [meta-command](https://www.postgresql.org/docs/9.6/static/app-psql.html) allows setting application name using a ["connection URI"](https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-CONNSTRING). 

Any application creating a connection can set the application name via connection info. I expect app name to then show up in the corresponding connection entry in the server log.
