### ISSUE TITLE
Function importLog will likely cause an undecipherable exception if log file is not found (M)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#165]
If connection logging is not enabled or log file names are not configured as expected, function [importLog](https://github.com/DASSL/ClassDB/blob/28faab780803f7bbda843d793fc013a9da0cc03c/src/addConnectionActivityLogging.sql#L111-L114) is likely raise an exception with a message that is not so helpful.

It might be helpful to first test if the result of the query `SELECT setting FROM pg_settings WHERE "name" = 'log_directory'` is not empty/NULL prior to entering the loop. If the result is empty/NULL we should probably raise a notice (exception?) that logging is not enabled or such.

It is also useful to understand what COPY does if the file path provided does not exist. Perhaps we can raise a custom exception.

I don't think we should try any of this for M2.

**Comment by srrollo** [comment]
This is likely covered by #200, but I will add it to the epic as well.
