### ISSUE TITLE
Script-kind specific preparation scripts are unavailable (M)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#166]
It will be helpful to have scripts `addAllDBCore.psql`, `addAllDBReco.psql`, `addAllDBOpt.psql` in each kind-specific sub-directory. For uniformity and ease of documentation, these files can exist even if there is only one script in a sub-directory.

`addAllDBCore.psql` is the same as the current `prepardDB.psql`.

Likewise for kind-specific sub-directories for the server.

**Comment by KevinKelly25** [comment]
Added with PR #167
