### ISSUE TITLE
Some installation files are missing or have incorrect names (WM)

### ISSUE THREAD

**Issue by srrollo** [DASSL/ClassDB#185]
There are no installation scripts for installing all components at once, and one installation script has an incorrect name.
A proposed solution is:
1. [x] `prepareServerCore.sql` => `initializeServerCore.sql`
2. [x] Add `addAllDB.psql`, which installs all DB components
3. [x] Add `addAllServer.psql` which installs all server components

The two new installer scripts should call the existing `addAllXY.psql` scripts instead of individual sql files.

**Comment by smurthys** [comment]
Related to this issue, as discussed yesterday, the Quick Start doc also needs to be changed to show installation of all scripts.

**Comment by srrollo** [comment]
One other thing I've noticed:
- Should we change `removeAllFrom[DB/Server]` to `removeAll[DB/Server]`, since this will match the name of the new install script: `addAll[DB/Server]`?

**Comment by smurthys** [comment]
Renaming `removeAllFrom[DB/Server]` to `removeAll[DB/Server]` seems OK.

**Comment by smurthys** [comment]
In retrospect, I worry `removeAll[DB/Server]` could be misconstrued as meaning "remove all DBs/servers". Maybe the better approach is to say `addAlTo[DB/Server]`, even though it has a different form than the other add scripts.

I am sorry I did not state this possibility earlier (too much multi-tasking go on).
