### ISSUE TITLE
Some scripts reference incorrect file names (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#212]
Some script files, for example [addClassDBRolesMgmtCore.sql](https://github.com/DASSL/ClassDB/blob/14eb33909f670c0689a791e32dbd4bd3cd596784/src/db/core/addClassDBRolesMgmtCore.sql), contain incorrect file names. The error seems to have crept in when scripts were re-organized into components.

I am not sure how we go about **efficiently** finding all such errors.

**Comment by KevinKelly25** [comment]
Using Atoms search function to look for all .sql and .psql mentions in the project I found errors in the projects. Here they are

**docs\Activity-Logging**
- enableServerLogging
- addDDLMonitors
- addLogMgmt

**docs\Managing-Log-Files**
- enableServerLogging

**docs\Scripts**
- prepareServerCore
- worth noting this has createShelterSchema.sql and associated example files that as discussed in meeting might be removed

**docs\Scripts**
- removeAllFromDB is spelled incorrectly twice

**tests\testAddConnectionActivityLoggingCleanup.sql**
- testAddLogMgmt

I will fix all these files that I have found but this may not cover all the errors in the documentation if they were not followed by a .sql or .psql for some reason.

**Comment by smurthys** [comment]
Good find @KevinKelly25. It is interesting the result does not include any file in the `src` directory tree though there is at least one source file with the issue. Would you look into that please?

**Comment by KevinKelly25** [comment]
I actually just didn't add that to the list because it was mentioned in the first post. I did however, find one more in the src files that I missed. I will add both to the list above for clarity.

**Comment by smurthys** [comment]
Thanks @KevinKelly25  for adding src files to the list.

Please change doc files in the Wiki. Also, I recommend delaying the src file changes until there is a quiescent point, because these kinds of changes can easily cause merge conflicts.

(PS: It helps to add an "EDIT" note to an edited comment so later comments don't look out of place.)

**Comment by KevinKelly25** [comment]
Updated the docs to correct the issues. Added strike through for the above list for corrections already made.
