### ISSUE TITLE
File addUserMgmtCore.sql defines objects used only by reco scripts (WE)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#217]
The script file [`addUserMgmtCore.sql`](https://github.com/DASSL/ClassDB/blob/4536a255fd67daf2e68ceab0a88dbfcbe7d46f92/src/db/core/addUserMgmtCore.sql) defines objects not used by any core component.

I propose the following changes:
- [ ] Move the definition of table `DDLActivity` to `addDDLActivityLoggingReco.sql`
- [ ] Move the definition of table `ConnectionActivity` to `addConnectionActivityLoggingReco.sql`
- [ ] Move the remaining code to a new file `addLogProtectionReco.sql` (or such)

EDIT: See [comment below](https://github.com/DASSL/ClassDB/issues/217#issuecomment-396539274) on a resolution that leaves the file as is, and addresses the issue by just adding comments.

**Comment by srrollo** [comment]
I think the difficulty with this change is that ClassDB.User depends on both activity tables. We could switch to a modular setup where the new suggested scripts execute ALTER VIEW statements to add the relevant query over each activity table. 

Additionally, the Activity Views rely on the activity columns in Class DB.User, so Class DB.User would need blank/dummy columns in case activity logging components are not installed.

**Comment by smurthys** [comment]
Thanks @srrollo for refreshing my memory. I do now recall this before M2 and deciding to postpone due to time constraint. I suppose we have to do that again. However this time we at least have an issue logged.

**Comment by smurthys** [comment]
For M3, I suggest we **add comments to the file in question to clearly say why it is a core component**. Without such comments, this issue will come up repeatedly and consume valuable research/discussion time.
