### ISSUE TITLE
Add session id to table DDLActivity (N)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#237]
Adding column `SessionID` to table `DDLActivity` makes it possible to connect each DDL acitivity to an application and a connection. This information is necessary for analysis operations.

Postgres doesn't have a function to get session id, but the following query (based on [pg doc for `log_line_prefix`](https://www.postgresql.org/docs/9.6/static/runtime-config-logging.html)) should work:

```sql
SELECT to_hex(trunc(EXTRACT(EPOCH FROM backend_start))::integer) || '.' ||
       to_hex(pid)
FROM pg_stat_activity
WHERE pid = pg_backend_pid();
```

**Comment by srrollo** [comment]
Oh I understand the function now. I had mentioned in #235 that this function might be an issue, however I didn't realize that pg_stat_activity exposes backend_start. I will confirm that this function produces a matching session ID.

**Comment by smurthys** [comment]
Adding `SessionID` to `DDLActivity` changes many functions and views, and needs many documentation changes. However, the changes are well defined and can be done in M3.

Also, making this change now prevents later API-compatibility issues. So, we should try to get this done in M3.
