### ISSUE TITLE
Function dropUser in prepareClassDB.sql is unused (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#43]
It looks like the function `dropUser` could be called (with some revision if necessary) from functions `dropStudent`, `dropInstructor`, and `dropDBManager `(each of which have quite a bit of repeated code).

**Comment by smurthys** [comment]
Changing priority to low because this issue should be fixed with the new user/team management.

**Comment by afig** [comment]
Closing this as the new user/team management effectively solves this by having dropXYZ functions in `classDBRolesMgmt` that all use the dropRole function in `addRoleBaseMgmt`. See PR #143 and #155 for more information on the new user/team management.
