### ISSUE TITLE
Column name classDB.Student.schoolID is misleading (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#45]
The column name classDB.Student.schoolID can be construed as the "ID of the student's school", instead of "the student's school-issued ID". I don't presently have alternatives to suggest.

**Comment by smurthys** [comment]
`orgIssuedID` sounds like a neutral enough and appropriate name.

With v1.0.0 already released, making this change also requires writing a script to patch existing installations.

**Comment by smurthys** [comment]
Changing priority to low because the new user/team mgmt approach should fix this issue.

**Comment by afig** [comment]
I propose closing this once #159 is merged in, as that implements the Student view that replaces the table this column was part of.
