### ISSUE TITLE
Tables Student and Instructor contain similar information and cause redundant code (E)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#49]
I propose merging the tables `Student` and `Instructor` to a single `User` table. This unification eliminates some repeated code, simplifies some operations, and provides connection/DLL tracking for all users. (The unified table will probably also add more parameters to existing functions.)

**Comment by smurthys** [comment]
I just added a branch [add-RoleBase-Mgmt](https://github.com/DASSL/ClassDB/tree/68c8a099f0ad7f73448bf9c0e123e5da529c3c80) to address this and the following related issues: #42, #43, #45, #134, #137 

The branch has the following commits:
- d99a211 Edited `addHelpers.sql` to meet needs of new user/team mgmt.
- 526d9ed Added initial version of `addRoleBaseMgmt.sql` for new user/team mgmt.
- 746e9e2 Included `addRoleBaseMgmt.sql` to `prepareDB.psql`
- 79ebb9a and 68c8a09 Updates addUserMgmt.sql to replace calls to function `isRoleDefined` with calls to `isServerRoleDefined` because that function is renamed in `addHelpers.sql`

The file `addRoleBaseMgmt.sql` is virtually 100% new and is a **major development**. (It took me about 4 days of practically exclusive attention.)

As the commit message for 526d9ed says, I have made sure everything compiles, but I have done only a cursory test, and I am still developing a test script. I expect that will take me a day or so worth of work before the test covers all possible cases. The good news is that the cursory test shows many of the nifty features actually appear to work. 😊 

It will be extremely helpful if all contributors look at the code and add comments directly at commit 526d9ed. Because this code is central to ClassDB, we can benefit from every kind of feedback. Thank you all in advance.

BTW, I am fairly confident we can safely merge the files in these commits into the current master. However, I am intentionally delaying creating a PR until I have created the test script.

**Comment by smurthys** [comment]
I just pushed commit fcdbc7f to the [add-RoleBase-Mgmt](https://github.com/DASSL/ClassDB/tree/68c8a099f0ad7f73448bf9c0e123e5da529c3c80) branch. 

This commit renames the script `addUserMgmt.sql` to `addClassDBRolesMgmt.sql` to make it easier to merge the upcoming changes.

The summary of changes to come: The future `addUserMgmt.sql` will be about managing users (as opposed to teams) and will use the functionality in `addRoleBaseMgmt.sql`. Its content will be quite different from what is presently in `addUserMgmt.sql`.

The script `addClassDBRolesMgmt.sql` will have functionality specific to instructors, students, and db managers.

**Comment by smurthys** [comment]
Changing priority to low because the new user/team mgmt approach should fix this issue.

**Comment by srrollo** [comment]
I believe this can be closed now that the new user role base system has been merged.
