### ISSUE TITLE
Function prologue comments interfere with DROP-CREATE combo (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#67]
Presently, function prologue comments appear between `DROP FUNCTION` and its corresponding `CREATE FUNCTION` with no white space in between. This organization makes it hard to read the comment and also does not highlight that the drop and create are correlated.

 I recommend putting function-prologue comments just before the `DROP FUNCTION`, effectively treating `DROP FUNCTION` and the following `CREATE FUNCTION` as one unit.

**Comment by smurthys** [comment]
I believe this issue is addressed, but not sure why it is not closed.

**Comment by srrollo** [comment]
It looks like the commit message from 94a1086 was intended to auto-close this issue, however GitHub did not pick up on it. I think it is appropriate to manually close it now.

**Comment by smurthys** [comment]
I agree  Commit 94a1086 fixes this issue. Closing the issue.
